### ISSUE TITLE
make option to change the path for tsc

### ISSUE THREAD

**Issue by lunelson** [misaxi/sublime-code-preview#10]
I've installed typescript using npm, but this plugin doesn't pick it up. Seems it's not looking in the right place for it. Could it be updated for npm-installed packages or have an option to set an install path?

**Comment by misaxi** [comment]
Hi @lunelson , make sure if you can access tsc from the command line

```
> npm install -g typescript
> tsc
Version 0.9.5.0
Syntax:   tsc [options] [file ..]

Examples: tsc hello.ts
          tsc --out foo.js foo.ts
          tsc @args.txt
```

**Comment by lunelson** [comment]
Yes I can access it from the command line, I get the same result as above
