### ISSUE TITLE
Filename with .js.coffee in them will not get converted

### ISSUE THREAD

**Issue by cfurrow** [misaxi/sublime-code-preview#4]
I noticed that when files were named "main.js.coffee" they would not be compiled to js, and shown in the second view. but if I renamed the file to "main.coffee" and saved, it would immediately show up in the second view.

I found that this is because of how the file name and extension are being parsed.

The current method does a split on '.'

```
#filename = main.js.coffee
name,ext = filename.split('.') # => [main,js.coffee]
```

That would fail because name would be "main" and ext would be "js" which is not true. The extension is "coffee".

I'll create a pull request to try and fix this.

**Comment by cfurrow** [comment]
My PR #5 will fix this issue, but coffeescript will save a file named "main.js.coffee" to "main.js.js". That's its default behavior. But, the compiled file will be shown in Sublime Text 2 with this fix.

**Comment by misaxi** [comment]
Thanks Carl for the awesome fix! Appreciate it.

**Comment by cfurrow** [comment]
No problem. Beauty of open source :octocat:
